/*
 * SPDX-FileCopyrightText: 2025 Roland Rusch, easy-smart solution GmbH <roland.rusch@easy-smart.ch>
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef LIBSMART_STM32FINGERPRINT_LIBSMART_CONFIG_DIST_HPP
#define LIBSMART_STM32FINGERPRINT_LIBSMART_CONFIG_DIST_HPP


#define LIBSMART_STM32FINGERPRINT

#define LIBSMART_STM32FINGERPRINT_INITIALIZE_WAIT_MS 200




#define LIBSMART_STM32FINGERPRINT_SETUP_WAIT_MS 200
#define LIBSMART_STM32FINGERPRINT_READY_WAIT_MS 10
#define LIBSMART_STM32FINGERPRINT_STANDBY_TIMEOUT_MS 10000


#endif
